#!/bin/sh
dmenu_path() {
	cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
	cache="$cachedir/dmenu_run"

	[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

	IFS=:
        # shellcheck disable=SC2086
	if stest -dqr -n "$cache" $PATH > /dev/null 2>&1; then
		stest -flx $PATH | sort -u | tee "$cache"
	else
		cat "$cache"
	fi
}

cmd=$(dmenu_path | dmenu "$@")

case $cmd in
	*\!) "${TERMINAL:-st}" -e "${cmd%?}" & ;;
	*) test "$cmd" && "$cmd" & ;;
esac
